[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  branch = "features/pojo"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-docker"

[[override]]
  branch = "master"
  name = "github.com/docker/docker"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"
